language: java
sudo: false

install: /bin/true

jdk:
- oraclejdk8

services:
  - mongodb

before_install:
- gradle wrapper

before_script:
    - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
    - wget https://services.gradle.org/distributions/gradle-2.14-bin.zip
    - unzip gradle-2.14-bin.zip
    - export GRADLE_HOME=$PWD/gradle-2.14
    - export PATH=$GRADLE_HOME/bin:$PATH

script:
- ./gradlew assemble
- ./gradlew check
